name: Add Latest Tag to Github # Test if the new commits has the version bump for deploy works
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - production
      - master
      - main

jobs:
  tagging-job:
    runs-on: ubuntu-latest
    name: Adds latest tag
    steps:
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag with this input.
          # Default: 'latest'
          # tag-name: someCustomTagName

          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Optional
          description: Latest Version
